-- CreateTable
CREATE TABLE "DISTRITOS" (
    "DisCod" SERIAL NOT NULL,
    "DisNom" TEXT NOT NULL,

    CONSTRAINT "DISTRITOS_pkey" PRIMARY KEY ("DisCod")
);

-- CreateTable
CREATE TABLE "CALIFICACIONES" (
    "CalCod" SERIAL NOT NULL,
    "CalMeGus" INTEGER NOT NULL,
    "CalNoGus" INTEGER NOT NULL,

    CONSTRAINT "CALIFICACIONES_pkey" PRIMARY KEY ("CalCod")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "UsuCod" SERIAL NOT NULL,
    "UsuNom" TEXT NOT NULL,
    "UsuCor" TEXT NOT NULL,
    "UsuCon" TEXT NOT NULL,
    "DisCod" INTEGER NOT NULL,
    "UsuFotURL" TEXT NOT NULL,
    "UsuFecNacAno" INTEGER NOT NULL,
    "UsuFecNacMes" INTEGER NOT NULL,
    "UsuFecNacDia" INTEGER NOT NULL,

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("UsuCod")
);

-- CreateTable
CREATE TABLE "PASEADORES" (
    "PasCod" SERIAL NOT NULL,
    "PasNom" TEXT NOT NULL,
    "PasCor" TEXT NOT NULL,
    "PasCon" TEXT NOT NULL,
    "DisCod" INTEGER NOT NULL,
    "PasFotURL" TEXT NOT NULL,
    "PasFecNacAno" INTEGER NOT NULL,
    "PasFecNacMes" INTEGER NOT NULL,
    "PasFecNacDia" INTEGER NOT NULL,
    "PasDes" TEXT NOT NULL,
    "PasDis" TEXT NOT NULL,
    "CalCod" INTEGER NOT NULL,

    CONSTRAINT "PASEADORES_pkey" PRIMARY KEY ("PasCod")
);

-- CreateTable
CREATE TABLE "MASCOTAS" (
    "MasCod" SERIAL NOT NULL,
    "MasNom" TEXT NOT NULL,
    "MasCol" TEXT NOT NULL,
    "MasRaz" TEXT NOT NULL,
    "MasEda" INTEGER NOT NULL,
    "MasFotURL" TEXT NOT NULL,
    "MasDes" TEXT NOT NULL,
    "MasIsToAdo" BOOLEAN NOT NULL,
    "MasUsuCod" INTEGER NOT NULL,

    CONSTRAINT "MASCOTAS_pkey" PRIMARY KEY ("MasCod")
);

-- CreateTable
CREATE TABLE "PASEOS" (
    "PasNum" SERIAL NOT NULL,
    "PasCod" INTEGER NOT NULL,
    "UsuCod" INTEGER NOT NULL,
    "PasDis" TEXT NOT NULL,
    "PasDir" TEXT NOT NULL,
    "PasFecAno" INTEGER NOT NULL,
    "PasFecMes" INTEGER NOT NULL,
    "PasFecDia" INTEGER NOT NULL,
    "PasHor" TEXT NOT NULL,
    "PasCanHor" INTEGER NOT NULL,
    "PasEst" TEXT NOT NULL DEFAULT 'P',

    CONSTRAINT "PASEOS_pkey" PRIMARY KEY ("PasNum")
);

-- CreateTable
CREATE TABLE "PASEOS_MASCOTAS" (
    "PasNum" INTEGER NOT NULL,
    "MasCod" INTEGER NOT NULL,

    CONSTRAINT "PASEOS_MASCOTAS_pkey" PRIMARY KEY ("PasNum","MasCod")
);

-- CreateTable
CREATE TABLE "COMENTARIOS" (
    "ComCod" SERIAL NOT NULL,
    "UsuCod" INTEGER NOT NULL,
    "PasCod" INTEGER NOT NULL,
    "ComIsLike" BOOLEAN NOT NULL,
    "ComTex" TEXT NOT NULL,

    CONSTRAINT "COMENTARIOS_pkey" PRIMARY KEY ("ComCod")
);

-- CreateTable
CREATE TABLE "TRAMITES" (
    "TraCod" SERIAL NOT NULL,
    "TraUsuCodAdo" INTEGER NOT NULL,
    "TraUsuCodDue" INTEGER NOT NULL,
    "TraFecAno" INTEGER NOT NULL,
    "TraFecMes" INTEGER NOT NULL,
    "TraFecDia" INTEGER NOT NULL,
    "TraMasCod" INTEGER NOT NULL,
    "TraEst" TEXT NOT NULL DEFAULT 'P',

    CONSTRAINT "TRAMITES_pkey" PRIMARY KEY ("TraCod")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_UsuCor_key" ON "USUARIOS"("UsuCor");

-- CreateIndex
CREATE UNIQUE INDEX "PASEADORES_PasCor_key" ON "PASEADORES"("PasCor");

-- AddForeignKey
ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_DisCod_fkey" FOREIGN KEY ("DisCod") REFERENCES "DISTRITOS"("DisCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASEADORES" ADD CONSTRAINT "PASEADORES_DisCod_fkey" FOREIGN KEY ("DisCod") REFERENCES "DISTRITOS"("DisCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASEADORES" ADD CONSTRAINT "PASEADORES_CalCod_fkey" FOREIGN KEY ("CalCod") REFERENCES "CALIFICACIONES"("CalCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MASCOTAS" ADD CONSTRAINT "MASCOTAS_MasUsuCod_fkey" FOREIGN KEY ("MasUsuCod") REFERENCES "USUARIOS"("UsuCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASEOS" ADD CONSTRAINT "PASEOS_PasCod_fkey" FOREIGN KEY ("PasCod") REFERENCES "PASEADORES"("PasCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASEOS" ADD CONSTRAINT "PASEOS_UsuCod_fkey" FOREIGN KEY ("UsuCod") REFERENCES "USUARIOS"("UsuCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASEOS_MASCOTAS" ADD CONSTRAINT "PASEOS_MASCOTAS_PasNum_fkey" FOREIGN KEY ("PasNum") REFERENCES "PASEOS"("PasNum") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASEOS_MASCOTAS" ADD CONSTRAINT "PASEOS_MASCOTAS_MasCod_fkey" FOREIGN KEY ("MasCod") REFERENCES "MASCOTAS"("MasCod") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMENTARIOS" ADD CONSTRAINT "COMENTARIOS_UsuCod_fkey" FOREIGN KEY ("UsuCod") REFERENCES "USUARIOS"("UsuCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMENTARIOS" ADD CONSTRAINT "COMENTARIOS_PasCod_fkey" FOREIGN KEY ("PasCod") REFERENCES "PASEADORES"("PasCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_TraUsuCodAdo_fkey" FOREIGN KEY ("TraUsuCodAdo") REFERENCES "USUARIOS"("UsuCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_TraUsuCodDue_fkey" FOREIGN KEY ("TraUsuCodDue") REFERENCES "USUARIOS"("UsuCod") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRAMITES" ADD CONSTRAINT "TRAMITES_TraMasCod_fkey" FOREIGN KEY ("TraMasCod") REFERENCES "MASCOTAS"("MasCod") ON DELETE RESTRICT ON UPDATE CASCADE;
